# Generated by Django 5.0.7 on 2024-11-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
